version: '3.8'

networks:
  stalker:
    name: stalker
    ipam:
      config:
      - subnet: 19.19.19.0/24

services:
  e2e:
    image: node:alpine
    entrypoint: /bin/sh -c 'yarn install; tail -f'
    volumes:
    - .:/ws
    working_dir: /ws/e2e
    networks:
      stalker:
        ipv4_address: 19.19.19.2

  hub:
    image: selenium/hub:3.141.59
    ports:
    - 4444
    networks:
      stalker:
        ipv4_address: 19.19.19.10

  chrome:
    image: selenium/node-chrome-debug:3.141.59
    ports:
    - 5900
    volumes:
    - .:/ws
    environment:
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444
    - SCREEN_WIDTH=2000
    - SCREEN_HEIGHT=2000
    networks:
      stalker:
        ipv4_address: 19.19.19.11

  app:
    image: node:alpine
    entrypoint: /bin/sh -c 'yarn install && yarn start; tail -f'
    stdin_open: true
    volumes:
    - .:/ws
    working_dir: /ws/app
    ports:
    - 3000
    environment:
    - PORT=3000
    - HOST=0.0.0.0
    networks:
      stalker:
        ipv4_address: 19.19.19.19

  api:
    image: node:alpine
    entrypoint: /bin/sh -c 'yarn install && yarn dev; tail -f'
    volumes:
    - .:/ws
    working_dir: /ws/api
    ports:
    - 5000
    environment:
    - PORT=5000
    - HOST=0.0.0.0
    networks:
      stalker:
        ipv4_address: 19.19.19.20

