version: '3.8'

services:
  e2e:
    image: node:alpine
    entrypoint: /bin/sh -c 'yarn install; tail -f'
    volumes:
    - .:/ws
    working_dir: /ws/e2e

  hub:
    image: selenium/hub:3.141.59
    ports:
    - 4444
